name: Format go code

on: [push, pull_request_target]

jobs:
  format-go-code:
    name: Format go code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
      
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Install gofumpt
        run: go install mvdan.cc/gofumpt@latest

      - name: Format
        run: gofumpt -l -w .

      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore(style): format code'